name = "QuDiffEq"
uuid = "c02438fe-7edc-11e9-0a49-b5c5aafabe04"
authors = ["Divyanshu Gupta"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
